apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hola-api-serverless
  namespace: dotnet-hector
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/dotnet-hector/capacitacion
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8080